name: Ruff
on: [ push, pull_request ]
jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: chartboost/ruff-action@v1
        with:
          args: format
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install dependencies
        run: |
            pip install jupyter
            jupyter nbconvert --clear-output --inplace *.ipynb
      - uses: stefanzweifel/git-auto-commit-action@v5
        with: 
          commit_message: Formatted code